### ISSUE TITLE
I get PKCS#7 signature not signed with a trusted key

### ISSUE THREAD

**Issue by francescortiz** [juhovh/xmm7360_usb#2]
I have been able to install and load the driver, but I get the PKCS#7 signature not signed with a trusted key. I was also getting this with the xmm2usb project. I had to manually created a certificate in order to compile the module. I am using ubuntu. I have a Lenovo T480. Do you have any idea of what could be wrong? Thanks!

**Comment by juhovh** [comment]
This is because you have secure boot enabled and your operating system only allows you to load modules signed by the upstream. For more information see https://unix.stackexchange.com/questions/455189/pkcs7-signature-not-signed-with-a-trusted-key

Easiest way would be to disable secure boot, but there is also the better process of signing the modules and registering the key to the kernel https://ubuntu.com/blog/how-to-sign-things-for-secure-boot. That is a bit more complicated though.

**Comment by francescortiz** [comment]
Thanks!
